# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dff90f4ba9008429c4c00438a65ceb7bba13e9a8e026b58c623c85c92da4ef384957153093e13134b47728fd72c5e6a84cc3807dd949ba271217b9b113b3c26

test:
  secret_key_base: b51c0b4f75a1b3a21b0cf215c4c34603ca26c2c3384d4b2d8eab6a4facd65efb8b4cf4384f0ebe1af4b45173dbaa943eb9b666127e8816eb1b02355b34e6d7d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
